### ISSUE TITLE
Without mount vigor bar stops at 4, even when 5 are skilled

### ISSUE THREAD

**Issue by tiramon** [AzerPUG/DragonRiding#6]
When i sit in my mount it shows me 5/5 vigor, when i dismount i only see 4/4 vigor

**Comment by Arco-Dielhof** [comment]
The AddOn does only detect on load how much total vigor you have. Since it only happens a total of 3 times (3 to 4, 4 to 5 and 5 to 6) and most people get all the glyphs the moment they unlock dragon riding, it was not worth fixing this non-lethal issue, since a simple reload fixes it. Once you get to 6, reload, and you will never have to worry about it again (unless Blizz makes a 7th at some point ;) )
